name: Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
        
      - name: Get Changed Files
        id: git-changes
        run: |
          git log --oneline -n 5  # Вывести последние 5 коммитов для отладки
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed Files:"
          echo "${CHANGED_FILES}"
          echo "::set-output name=files::${CHANGED_FILES}"

      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: "@githublogs"
        run: |
          echo "New commit pushed to main branch on GitHub!"
          echo "Changed Files:"
          echo "${{ steps.git-changes.outputs.files }}"
          cat message.txt | curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -d "chat_id=${TELEGRAM_CHAT_ID}" -d "text=$(cat message.txt)"
