name: Telegram Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: "@githublogs"
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          # echo "New commit pushed to <a href='https://github.com/goodven152/pythonProjects'><b>main</b></a> branch on GitHub!%0A%0A<i>This message was generated automatically%0ACommit Message: $COMMIT_MESSAGE</i>"
          # echo "Commit Message: $COMMIT_MESSAGE" > message.txt
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" -d "chat_id=${TELEGRAM_CHAT_ID}" -d "text=New commit pushed to <a href='https://github.com/goodven152/pythonProjects'><b>main</b></a> branch on GitHub!%0A%0ACommit Message: $COMMIT_MESSAGE%0A<i>This message was generated automatically</i>" -d "disable_notification=true" -d "parse_mode=HTML"
          # curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" -d "chat_id=${TELEGRAM_CHAT_ID}" -d "text=New commit pushed to <a href='https://github.com/goodven152/pythonProjects'><b>main</b></a> branch on GitHub!%0A%0A<i>This message was generated automatically%0ACommit Message: $COMMIT_MESSAGE</i>"
